<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data =
            [
            ["abbreviation" => "ab", "name" => "Abkhaz", "native_name" => "аҧсуа"],
            ["abbreviation" => "aa", "name" => "Afar", "native_name" => "Afaraf"],
            ["abbreviation" => "af", "name" => "Afrikaans", "native_name" => "Afrikaans"],
            ["abbreviation" => "ak", "name" => "Akan", "native_name" => "Akan"],
            ["abbreviation" => "sq", "name" => "Albanian", "native_name" => "Shqip"],
            ["abbreviation" => "am", "name" => "Amharic", "native_name" => "አማርኛ"],
            ["abbreviation" => "ar", "name" => "Arabic", "native_name" => "العربية"],
            ["abbreviation" => "an", "name" => "Aragonese", "native_name" => "Aragonés"],
            ["abbreviation" => "hy", "name" => "Armenian", "native_name" => "Հայերեն"],
            ["abbreviation" => "as", "name" => "Assamese", "native_name" => "অসমীয়া"],
            ["abbreviation" => "av", "name" => "Avaric", "native_name" => "авар мацӀ, магӀарул мацӀ"],
            ["abbreviation" => "ae", "name" => "Avestan", "native_name" => "avesta"],
            ["abbreviation" => "ay", "name" => "Aymara", "native_name" => "aymar aru"],
            ["abbreviation" => "az", "name" => "Azerbaijani", "native_name" => "azərbaycan dili"],
            ["abbreviation" => "bm", "name" => "Bambara", "native_name" => "bamanankan"],
            ["abbreviation" => "ba", "name" => "Bashkir", "native_name" => "башҡорт теле"],
            ["abbreviation" => "eu", "name" => "Basque", "native_name" => "euskara, euskera"],
            ["abbreviation" => "be", "name" => "Belarusian", "native_name" => "Беларуская"],
            ["abbreviation" => "bn", "name" => "Bengali", "native_name" => "বাংলা"],
            ["abbreviation" => "bh", "name" => "Bihari", "native_name" => "भोजपुरी"],
            ["abbreviation" => "bi", "name" => "Bislama", "native_name" => "Bislama"],
            ["abbreviation" => "bs", "name" => "Bosnian", "native_name" => "bosanski jezik"],
            ["abbreviation" => "br", "name" => "Breton", "native_name" => "brezhoneg"],
            ["abbreviation" => "bg", "name" => "Bulgarian", "native_name" => "български език"],
            ["abbreviation" => "my", "name" => "Burmese", "native_name" => "ဗမာစာ"],
            ["abbreviation" => "ca", "name" => "Catalan; Valencian", "native_name" => "Català"],
            ["abbreviation" => "ch", "name" => "Chamorro", "native_name" => "Chamoru"],
            ["abbreviation" => "ce", "name" => "Chechen", "native_name" => "нохчийн мотт"],
            ["abbreviation" => "ny", "name" => "Chichewa; Chewa; Nyanja", "native_name" => "chiCheŵa, chinyanja"],
            ["abbreviation" => "zh", "name" => "Chinese", "native_name" => "中文 (Zhōngwén), 汉语, 漢語"],
            ["abbreviation" => "cv", "name" => "Chuvash", "native_name" => "чӑваш чӗлхи"],
            ["abbreviation" => "kw", "name" => "Cornish", "native_name" => "Kernewek"],
            ["abbreviation" => "co", "name" => "Corsican", "native_name" => "corsu, lingua corsa"],
            ["abbreviation" => "cr", "name" => "Cree", "native_name" => "ᓀᐦᐃᔭᐍᐏᐣ"],
            ["abbreviation" => "hr", "name" => "Croatian", "native_name" => "hrvatski"],
            ["abbreviation" => "cs", "name" => "Czech", "native_name" => "česky, čeština"],
            ["abbreviation" => "da", "name" => "Danish", "native_name" => "dansk"],
            ["abbreviation" => "dv", "name" => "Divehi; Dhivehi; Maldivian;", "native_name" => "ދިވެހި"],
            ["abbreviation" => "nl", "name" => "Dutch", "native_name" => "Nederlands, Vlaams"],
            ["abbreviation" => "en", "name" => "English", "native_name" => "English"],
            ["abbreviation" => "eo", "name" => "Esperanto", "native_name" => "Esperanto"],
            ["abbreviation" => "et", "name" => "Estonian", "native_name" => "eesti, eesti keel"],
            ["abbreviation" => "ee", "name" => "Ewe", "native_name" => "Eʋegbe"],
            ["abbreviation" => "fo", "name" => "Faroese", "native_name" => "føroyskt"],
            ["abbreviation" => "fj", "name" => "Fijian", "native_name" => "vosa Vakaviti"],
            ["abbreviation" => "fi", "name" => "Finnish", "native_name" => "suomi, suomen kieli"],
            ["abbreviation" => "fr", "name" => "French", "native_name" => "français, langue française"],
            ["abbreviation" => "ff", "name" => "Fula; Fulah; Pulaar; Pular", "native_name" => "Fulfulde, Pulaar, Pular"],
            ["abbreviation" => "gl", "name" => "Galician", "native_name" => "Galego"],
            ["abbreviation" => "ka", "name" => "Georgian", "native_name" => "ქართული"],
            ["abbreviation" => "de", "name" => "German", "native_name" => "Deutsch"],
            ["abbreviation" => "el", "name" => "Greek, Modern", "native_name" => "Ελληνικά"],
            ["abbreviation" => "gn", "name" => "Guaraní", "native_name" => "Avañeẽ"],
            ["abbreviation" => "gu", "name" => "Gujarati", "native_name" => "ગુજરાતી"],
            ["abbreviation" => "ht", "name" => "Haitian; Haitian Creole", "native_name" => "Kreyòl ayisyen"],
            ["abbreviation" => "ha", "name" => "Hausa", "native_name" => "Hausa, هَوُسَ"],
            ["abbreviation" => "he", "name" => "Hebrew (modern)", "native_name" => "עברית"],
            ["abbreviation" => "hz", "name" => "Herero", "native_name" => "Otjiherero"],
            ["abbreviation" => "hi", "name" => "Hindi", "native_name" => "हिन्दी, हिंदी"],
            ["abbreviation" => "ho", "name" => "Hiri Motu", "native_name" => "Hiri Motu"],
            ["abbreviation" => "hu", "name" => "Hungarian", "native_name" => "Magyar"],
            ["abbreviation" => "ia", "name" => "Interlingua", "native_name" => "Interlingua"],
            ["abbreviation" => "id", "name" => "Indonesian", "native_name" => "Bahasa Indonesia"],
            ["abbreviation" => "ie", "name" => "Interlingue", "native_name" => "Originally called Occidental; then Interlingue after WWII"],
            ["abbreviation" => "ga", "name" => "Irish", "native_name" => "Gaeilge"],
            ["abbreviation" => "ig", "name" => "Igbo", "native_name" => "Asụsụ Igbo"],
            ["abbreviation" => "ik", "name" => "Inupiaq", "native_name" => "Iñupiaq, Iñupiatun"],
            ["abbreviation" => "io", "name" => "Ido", "native_name" => "Ido"],
            ["abbreviation" => "is", "name" => "Icelandic", "native_name" => "Íslenska"],
            ["abbreviation" => "it", "name" => "Italian", "native_name" => "Italiano"],
            ["abbreviation" => "iu", "name" => "Inuktitut", "native_name" => "ᐃᓄᒃᑎᑐᑦ"],
            ["abbreviation" => "ja", "name" => "Japanese", "native_name" => "日本語 (にほんご／にっぽんご)"],
            ["abbreviation" => "jv", "name" => "Javanese", "native_name" => "basa Jawa"],
            ["abbreviation" => "kl", "name" => "Kalaallisut, Greenlandic", "native_name" => "kalaallisut, kalaallit oqaasii"],
            ["abbreviation" => "kn", "name" => "Kannada", "native_name" => "ಕನ್ನಡ"],
            ["abbreviation" => "kr", "name" => "Kanuri", "native_name" => "Kanuri"],
            ["abbreviation" => "ks", "name" => "Kashmiri", "native_name" => "कश्मीरी, كشميري‎"],
            ["abbreviation" => "kk", "name" => "Kazakh", "native_name" => "Қазақ тілі"],
            ["abbreviation" => "km", "name" => "Khmer", "native_name" => "ភាសាខ្មែរ"],
            ["abbreviation" => "ki", "name" => "Kikuyu, Gikuyu", "native_name" => "Gĩkũyũ"],
            ["abbreviation" => "rw", "name" => "Kinyarwanda", "native_name" => "Ikinyarwanda"],
            ["abbreviation" => "ky", "name" => "Kirghiz, Kyrgyz", "native_name" => "кыргыз тили"],
            ["abbreviation" => "kv", "name" => "Komi", "native_name" => "коми кыв"],
            ["abbreviation" => "kg", "name" => "Kongo", "native_name" => "KiKongo"],
            ["abbreviation" => "ko", "name" => "Korean", "native_name" => "한국어 (韓國語), 조선말 (朝鮮語)"],
            ["abbreviation" => "ku", "name" => "Kurdish", "native_name" => "Kurdî, كوردی‎"],
            ["abbreviation" => "kj", "name" => "Kwanyama, Kuanyama", "native_name" => "Kuanyama"],
            ["abbreviation" => "la", "name" => "Latin", "native_name" => "latine, lingua latina"],
            ["abbreviation" => "lb", "name" => "Luxembourgish, Letzeburgesch", "native_name" => "Lëtzebuergesch"],
            ["abbreviation" => "lg", "name" => "Luganda", "native_name" => "Luganda"],
            ["abbreviation" => "li", "name" => "Limburgish, Limburgan, Limburger", "native_name" => "Limburgs"],
            ["abbreviation" => "ln", "name" => "Lingala", "native_name" => "Lingála"],
            ["abbreviation" => "lo", "name" => "Lao", "native_name" => "ພາສາລາວ"],
            ["abbreviation" => "lt", "name" => "Lithuanian", "native_name" => "lietuvių kalba"],
            ["abbreviation" => "lu", "name" => "Luba-Katanga", "native_name" => ""],
            ["abbreviation" => "lv", "name" => "Latvian", "native_name" => "latviešu valoda"],
            ["abbreviation" => "gv", "name" => "Manx", "native_name" => "Gaelg, Gailck"],
            ["abbreviation" => "mk", "name" => "Macedonian", "native_name" => "македонски јазик"],
            ["abbreviation" => "mg", "name" => "Malagasy", "native_name" => "Malagasy fiteny"],
            ["abbreviation" => "ms", "name" => "Malay", "native_name" => "bahasa Melayu, بهاس ملايو‎"],
            ["abbreviation" => "ml", "name" => "Malayalam", "native_name" => "മലയാളം"],
            ["abbreviation" => "mt", "name" => "Maltese", "native_name" => "Malti"],
            ["abbreviation" => "mi", "name" => "Māori", "native_name" => "te reo Māori"],
            ["abbreviation" => "mr", "name" => "Marathi (Marāṭhī)", "native_name" => "मराठी"],
            ["abbreviation" => "mh", "name" => "Marshallese", "native_name" => "Kajin M̧ajeļ"],
            ["abbreviation" => "mn", "name" => "Mongolian", "native_name" => "монгол"],
            ["abbreviation" => "na", "name" => "Nauru", "native_name" => "Ekakairũ Naoero"],
            ["abbreviation" => "nv", "name" => "Navajo, Navaho", "native_name" => "Diné bizaad, Dinékʼehǰí"],
            ["abbreviation" => "nb", "name" => "Norwegian Bokmål", "native_name" => "Norsk bokmål"],
            ["abbreviation" => "nd", "name" => "North Ndebele", "native_name" => "isiNdebele"],
            ["abbreviation" => "ne", "name" => "Nepali", "native_name" => "नेपाली"],
            ["abbreviation" => "ng", "name" => "Ndonga", "native_name" => "Owambo"],
            ["abbreviation" => "nn", "name" => "Norwegian Nynorsk", "native_name" => "Norsk nynorsk"],
            ["abbreviation" => "no", "name" => "Norwegian", "native_name" => "Norsk"],
            ["abbreviation" => "ii", "name" => "Nuosu", "native_name" => "ꆈꌠ꒿ Nuosuhxop"],
            ["abbreviation" => "nr", "name" => "South Ndebele", "native_name" => "isiNdebele"],
            ["abbreviation" => "oc", "name" => "Occitan", "native_name" => "Occitan"],
            ["abbreviation" => "oj", "name" => "Ojibwe, Ojibwa", "native_name" => "ᐊᓂᔑᓈᐯᒧᐎᓐ"],
            ["abbreviation" => "cu", "name" => "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", "native_name" => "ѩзыкъ словѣньскъ"],
            ["abbreviation" => "om", "name" => "Oromo", "native_name" => "Afaan Oromoo"],
            ["abbreviation" => "or", "name" => "Oriya", "native_name" => "ଓଡ଼ିଆ"],
            ["abbreviation" => "os", "name" => "Ossetian, Ossetic", "native_name" => "ирон æвзаг"],
            ["abbreviation" => "pa", "name" => "Panjabi, Punjabi", "native_name" => "ਪੰਜਾਬੀ, پنجابی‎"],
            ["abbreviation" => "pi", "name" => "Pāli", "native_name" => "पाऴि"],
            ["abbreviation" => "fa", "name" => "Persian", "native_name" => "فارسی"],
            ["abbreviation" => "pl", "name" => "Polish", "native_name" => "polski"],
            ["abbreviation" => "ps", "name" => "Pashto, Pushto", "native_name" => "پښتو"],
            ["abbreviation" => "pt", "name" => "Portuguese", "native_name" => "Português"],
            ["abbreviation" => "qu", "name" => "Quechua", "native_name" => "Runa Simi, Kichwa"],
            ["abbreviation" => "rm", "name" => "Romansh", "native_name" => "rumantsch grischun"],
            ["abbreviation" => "rn", "name" => "Kirundi", "native_name" => "kiRundi"],
            ["abbreviation" => "ro", "name" => "Romanian, Moldavian, Moldovan", "native_name" => "română"],
            ["abbreviation" => "ru", "name" => "Russian", "native_name" => "русский язык"],
            ["abbreviation" => "sa", "name" => "Sanskrit (Saṁskṛta)", "native_name" => "संस्कृतम्"],
            ["abbreviation" => "sc", "name" => "Sardinian", "native_name" => "sardu"],
            ["abbreviation" => "sd", "name" => "Sindhi", "native_name" => "सिन्धी, سنڌي، سندھی‎"],
            ["abbreviation" => "se", "name" => "Northern Sami", "native_name" => "Davvisámegiella"],
            ["abbreviation" => "sm", "name" => "Samoan", "native_name" => "gagana faa Samoa"],
            ["abbreviation" => "sg", "name" => "Sango", "native_name" => "yângâ tî sängö"],
            ["abbreviation" => "sr", "name" => "Serbian", "native_name" => "српски језик"],
            ["abbreviation" => "gd", "name" => "Scottish Gaelic; Gaelic", "native_name" => "Gàidhlig"],
            ["abbreviation" => "sn", "name" => "Shona", "native_name" => "chiShona"],
            ["abbreviation" => "si", "name" => "Sinhala, Sinhalese", "native_name" => "සිංහල"],
            ["abbreviation" => "sk", "name" => "Slovak", "native_name" => "slovenčina"],
            ["abbreviation" => "sl", "name" => "Slovene", "native_name" => "slovenščina"],
            ["abbreviation" => "so", "name" => "Somali", "native_name" => "Soomaaliga, af Soomaali"],
            ["abbreviation" => "st", "name" => "Southern Sotho", "native_name" => "Sesotho"],
            ["abbreviation" => "es", "name" => "Spanish; Castilian", "native_name" => "español, castellano"],
            ["abbreviation" => "su", "name" => "Sundanese", "native_name" => "Basa Sunda"],
            ["abbreviation" => "sw", "name" => "Swahili", "native_name" => "Kiswahili"],
            ["abbreviation" => "ss", "name" => "Swati", "native_name" => "SiSwati"],
            ["abbreviation" => "sv", "name" => "Swedish", "native_name" => "svenska"],
            ["abbreviation" => "ta", "name" => "Tamil", "native_name" => "தமிழ்"],
            ["abbreviation" => "te", "name" => "Telugu", "native_name" => "తెలుగు"],
            ["abbreviation" => "tg", "name" => "Tajik", "native_name" => "тоҷикӣ, toğikī, تاجیکی‎"],
            ["abbreviation" => "th", "name" => "Thai", "native_name" => "ไทย"],
            ["abbreviation" => "ti", "name" => "Tigrinya", "native_name" => "ትግርኛ"],
            ["abbreviation" => "bo", "name" => "Tibetan Standard, Tibetan, Central", "native_name" => "བོད་ཡིག"],
            ["abbreviation" => "tk", "name" => "Turkmen", "native_name" => "Türkmen, Түркмен"],
            ["abbreviation" => "tl", "name" => "Tagalog", "native_name" => "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"],
            ["abbreviation" => "tn", "name" => "Tswana", "native_name" => "Setswana"],
            ["abbreviation" => "to", "name" => "Tonga (Tonga Islands)", "native_name" => "faka Tonga"],
            ["abbreviation" => "tr", "name" => "Turkish", "native_name" => "Türkçe"],
            ["abbreviation" => "ts", "name" => "Tsonga", "native_name" => "Xitsonga"],
            ["abbreviation" => "tt", "name" => "Tatar", "native_name" => "татарча, tatarça, تاتارچا‎"],
            ["abbreviation" => "tw", "name" => "Twi", "native_name" => "Twi"],
            ["abbreviation" => "ty", "name" => "Tahitian", "native_name" => "Reo Tahiti"],
            ["abbreviation" => "ug", "name" => "Uighur, Uyghur", "native_name" => "Uyƣurqə, ئۇيغۇرچە‎"],
            ["abbreviation" => "uk", "name" => "Ukrainian", "native_name" => "українська"],
            ["abbreviation" => "ur", "name" => "Urdu", "native_name" => "اردو"],
            ["abbreviation" => "uz", "name" => "Uzbek", "native_name" => "zbek, Ўзбек, أۇزبېك‎"],
            ["abbreviation" => "ve", "name" => "Venda", "native_name" => "Tshivenḓa"],
            ["abbreviation" => "vi", "name" => "Vietnamese", "native_name" => "Tiếng Việt"],
            ["abbreviation" => "vo", "name" => "Volapük", "native_name" => "Volapük"],
            ["abbreviation" => "wa", "name" => "Walloon", "native_name" => "Walon"],
            ["abbreviation" => "cy", "name" => "Welsh", "native_name" => "Cymraeg"],
            ["abbreviation" => "wo", "name" => "Wolof", "native_name" => "Wollof"],
            ["abbreviation" => "fy", "name" => "Western Frisian", "native_name" => "Frysk"],
            ["abbreviation" => "xh", "name" => "Xhosa", "native_name" => "isiXhosa"],
            ["abbreviation" => "yi", "name" => "Yiddish", "native_name" => "ייִדיש"],
            ["abbreviation" => "yo", "name" => "Yoruba", "native_name" => "Yorùbá"],
            ["abbreviation" => "za", "name" => "Zhuang, Chuang", "native_name" => "Saɯ cueŋƅ, Saw cuengh"],
        ];

        Language::insert($data);

    }
}
